"""models updated

Revision ID: a42aa02f0231
Revises: 
Create Date: 2022-08-08 15:14:12.038584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a42aa02f0231'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('postid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('postcontent', sa.String(length=250), nullable=True),
    sa.Column('type', sa.Enum('userpost', 'grouppost', 'pagepost', 'sharedpagepost', 'shareduserpost', 'sharedgrouppost', name='posttype'), nullable=False),
    sa.PrimaryKeyConstraint('postid')
    )
    op.create_table('user',
    sa.Column('userid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=250), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.LargeBinary(length=1000), nullable=False),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('phoneno', sa.String(length=10), nullable=True),
    sa.Column('gender', sa.String(length=7), nullable=True),
    sa.Column('profile_image', sa.String(length=1000), nullable=True),
    sa.Column('cover_image', sa.String(length=1000), nullable=True),
    sa.Column('role', sa.Enum('admin', 'user', name='roletype'), nullable=False),
    sa.PrimaryKeyConstraint('userid'),
    sa.UniqueConstraint('email')
    )
    op.create_table('friend',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fk_user_from', sa.Integer(), nullable=False),
    sa.Column('fk_user_to', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fk_user_from'], ['user.userid'], ),
    sa.ForeignKeyConstraint(['fk_user_to'], ['user.userid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('friend_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('from_user', sa.Integer(), nullable=False),
    sa.Column('to_user', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('send', 'pending', 'accepted', 'rejected', name='statustype'), nullable=False),
    sa.ForeignKeyConstraint(['from_user'], ['user.userid'], ),
    sa.ForeignKeyConstraint(['to_user'], ['user.userid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group',
    sa.Column('groupid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('groupdescription', sa.String(length=2500), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('groupname', sa.String(length=250), nullable=False),
    sa.Column('group_cover_image', sa.String(length=10), nullable=True),
    sa.Column('group_profile_image', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.userid'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('groupid')
    )
    op.create_table('like',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.postid'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.userid'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'post_id')
    )
    op.create_table('page',
    sa.Column('pageid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pagedescription', sa.String(length=2500), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('pagename', sa.String(length=250), nullable=False),
    sa.Column('page_cover_image', sa.String(length=10), nullable=True),
    sa.Column('page_profile_image', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.userid'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pageid')
    )
    op.create_table('user_post',
    sa.Column('postid', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.userid'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['postid'], ['post.postid'], ),
    sa.PrimaryKeyConstraint('postid')
    )
    op.create_table('group_post',
    sa.Column('postid', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group.groupid'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['postid'], ['user_post.postid'], ),
    sa.PrimaryKeyConstraint('postid')
    )
    op.create_table('groupmember',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group.groupid'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.userid'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'group_id')
    )
    op.create_table('page_post',
    sa.Column('postid', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['page.pageid'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['postid'], ['post.postid'], ),
    sa.PrimaryKeyConstraint('postid')
    )
    op.create_table('pagefollower',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['page.pageid'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.userid'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'page_id')
    )
    op.create_table('pagelike',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['page.pageid'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.userid'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'page_id')
    )
    op.create_table('shared_user_post',
    sa.Column('postid', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.userid'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['postid'], ['user_post.postid'], ),
    sa.PrimaryKeyConstraint('postid')
    )
    op.create_table('shared_group_post',
    sa.Column('postid', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.userid'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['postid'], ['group_post.postid'], ),
    sa.PrimaryKeyConstraint('postid')
    )
    op.create_table('shared_page_post',
    sa.Column('postid', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.userid'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['postid'], ['page_post.postid'], ),
    sa.PrimaryKeyConstraint('postid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shared_page_post')
    op.drop_table('shared_group_post')
    op.drop_table('shared_user_post')
    op.drop_table('pagelike')
    op.drop_table('pagefollower')
    op.drop_table('page_post')
    op.drop_table('groupmember')
    op.drop_table('group_post')
    op.drop_table('user_post')
    op.drop_table('page')
    op.drop_table('like')
    op.drop_table('group')
    op.drop_table('friend_requests')
    op.drop_table('friend')
    op.drop_table('user')
    op.drop_table('post')
    # ### end Alembic commands ###
