"""db updated

Revision ID: b7208cb94552
Revises: 673ddd655426
Create Date: 2022-08-09 13:55:59.816084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7208cb94552'
down_revision = '673ddd655426'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('default_profile_image', sa.String(length=1000), nullable=True))
    op.add_column('user', sa.Column('default_cover_image', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'default_cover_image')
    op.drop_column('user', 'default_profile_image')
    # ### end Alembic commands ###
