"""models updated

Revision ID: c401dd3cc6d8
Revises: a42aa02f0231
Create Date: 2022-08-08 15:24:26.657869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c401dd3cc6d8'
down_revision = 'a42aa02f0231'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_comment',
    sa.Column('commentid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('comment_desc', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.postid'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.userid'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('commentid')
    )
    op.add_column('shared_group_post', sa.Column('shared_by', sa.Integer(), nullable=False))
    op.drop_constraint('shared_group_post_created_by_fkey', 'shared_group_post', type_='foreignkey')
    op.create_foreign_key(None, 'shared_group_post', 'user', ['shared_by'], ['userid'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('shared_group_post', 'created_by')
    op.add_column('shared_page_post', sa.Column('shared_by', sa.Integer(), nullable=False))
    op.drop_constraint('shared_page_post_created_by_fkey', 'shared_page_post', type_='foreignkey')
    op.create_foreign_key(None, 'shared_page_post', 'user', ['shared_by'], ['userid'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('shared_page_post', 'created_by')
    op.add_column('shared_user_post', sa.Column('shared_by', sa.Integer(), nullable=False))
    op.drop_constraint('shared_user_post_created_by_fkey', 'shared_user_post', type_='foreignkey')
    op.create_foreign_key(None, 'shared_user_post', 'user', ['shared_by'], ['userid'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('shared_user_post', 'created_by')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shared_user_post', sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'shared_user_post', type_='foreignkey')
    op.create_foreign_key('shared_user_post_created_by_fkey', 'shared_user_post', 'user', ['created_by'], ['userid'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('shared_user_post', 'shared_by')
    op.add_column('shared_page_post', sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'shared_page_post', type_='foreignkey')
    op.create_foreign_key('shared_page_post_created_by_fkey', 'shared_page_post', 'user', ['created_by'], ['userid'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('shared_page_post', 'shared_by')
    op.add_column('shared_group_post', sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'shared_group_post', type_='foreignkey')
    op.create_foreign_key('shared_group_post_created_by_fkey', 'shared_group_post', 'user', ['created_by'], ['userid'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('shared_group_post', 'shared_by')
    op.drop_table('post_comment')
    # ### end Alembic commands ###
